repos:
  - name: OpenvCloud Core
    source:
       branch: staging
    target:
       branch: master
    url: https://github.com/0-complexity/openvcloud
  - name: OpenvCloud Installer
    source:
       branch: master
    target:
       branch: master
    url: https://github.com/0-complexity/openvcloud_installer
  - name: OpenvCloud Frontend
    source:
       branch: staging
    target:
       branch: master
    url: https://github.com/0-complexity/g8vdc
  - name: OpenvCloud 0-Access
    source:
       branch: master
    target:
       branch: master
    url: https://github.com/0-complexity/0-access
  - name: OpenvCloud AYS
    source:
       branch: staging
    target:
       branch: master
    url: https://github.com/0-complexity/openvcloud_ays
    ays: true
  - name: OpenvCloud Selfhealing
    source:
       branch: staging
    target:
       branch: master
    url: https://github.com/0-complexity/selfhealing
  - name: JumpScale Core
    source:
       branch: staging
    target:
       branch: master
    url: https://github.com/jumpscale7/jumpscale_core7
  - name: JumpScale Portal
    source:
       branch: staging
    target:
       branch: master
    url: https://github.com/jumpscale7/jumpscale_portal
  - name: JumpScale AYS
    source:
       branch: staging
    target:
       branch: master
    ays: true
    url: https://github.com/jumpscale7/ays_jumpscale7

images:
  openvcloud/cb_master: 9.9.9
  openvcloud/js7: 9.9.9
  openvcloud/grafana-init: 9.9.9
  openvcloud/syncthing_sidecar: 9.9.9
  openvcloud/pxeboot: 9.9.9
  openvcloud/pxeboot-init: 9.9.9
  openvcloud/pxeboot-base: 2.4.0
  openvcloud/pxeboot-httpd: 9.9.9
  openvcloud/nginx-init: 9.9.9
  openvcloud/0-access: 9.9.9
  openvcloud/management: 9.9.9
  openvcloud/ninstaller: 9.9.9
  grafana/grafana: 5.0.0
  mongo: 3.7.2
  cvallance/mongo-k8s-sidecar: 9.9.9
  influxdb: 1.4
  syncthing/syncthing: 9.9.9
  redis: 3.2
